In [2]:
import os

def list_files(directory):
    try:
        # List all files in the given directory
        files = [f for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]
        return files
    except Exception as e:
        return str(e)  # Return the error message as a string

def list_directories(path='.'):
    return [d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d))]

# Example usage:
directory_path = "C:/Users/dnnxl/Documents/GitHub/drone-sort/dataset/DJI_20240308111117_0010_V_1/valid/images"
files_in_directory = [os.path.join(directory_path, file) for file in list_files(directory_path)]

In [18]:
from ultralytics import YOLO, RTDETR
# Load the weights of the YOLO model
model = YOLO("C:/Users/dnnxl/Documents/GitHub/drone-sort/weights/yolo11n/weights/best.pt")

In [19]:
results = model([files_in_directory[158]], iou=0.5, conf=0.3)


0: 384x640 3 pineapples, 140.9ms
Speed: 7.0ms preprocess, 140.9ms inference, 4.0ms postprocess per image at shape (1, 3, 384, 640)


In [20]:
for result in results:
    for bbox in result.boxes.xyxy:
        print(bbox.cpu().detach().numpy())

[     268.37      3.9925      434.58      262.52]
[     1324.9      351.98        1478      628.72]
[     694.94      161.84      998.54      621.84]


In [24]:
results[0].boxes.xyxy.cpu().detach().numpy()

array([[     268.37,      3.9925,      434.58,      262.52],
       [     1324.9,      351.98,        1478,      628.72],
       [     694.94,      161.84,      998.54,      621.84]], dtype=float32)

In [22]:
len(results)

1

In [25]:
sorted(os.listdir("C:/Users/dnnxl/Documents/GitHub/drone-sort/dataset/DJI_20240308111117_0010_V_1/train/images"))

['frame_00001.png',
 'frame_00002.png',
 'frame_00003.png',
 'frame_00004.png',
 'frame_00005.png',
 'frame_00006.png',
 'frame_00007.png',
 'frame_00008.png',
 'frame_00009.png',
 'frame_00010.png',
 'frame_00011.png',
 'frame_00012.png',
 'frame_00013.png',
 'frame_00014.png',
 'frame_00015.png',
 'frame_00016.png',
 'frame_00017.png',
 'frame_00018.png',
 'frame_00019.png',
 'frame_00020.png',
 'frame_00021.png',
 'frame_00022.png',
 'frame_00023.png',
 'frame_00024.png',
 'frame_00025.png',
 'frame_00026.png',
 'frame_00027.png',
 'frame_00028.png',
 'frame_00029.png',
 'frame_00030.png',
 'frame_00031.png',
 'frame_00032.png',
 'frame_00033.png',
 'frame_00034.png',
 'frame_00035.png',
 'frame_00036.png',
 'frame_00037.png',
 'frame_00038.png',
 'frame_00039.png',
 'frame_00040.png',
 'frame_00041.png',
 'frame_00042.png',
 'frame_00043.png',
 'frame_00044.png',
 'frame_00045.png',
 'frame_00046.png',
 'frame_00047.png',
 'frame_00048.png',
 'frame_00049.png',
 'frame_00050.png',
